test5/my_app/urls.py
from django.urls import path
from my_app import views

# TEMPLATE URLS!
app_name = "my_app"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="user_login")
]

test5/test5/urls.py
from django.contrib import admin
from django.urls import path, include
from my_app import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('logout/', views.user_logout, name="logout"),
    path('special/', views.special, name="special")
]

test5/my_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', 
                                    blank=True)
    
    def __str__(self):
        return self.user.username
    

test5/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        all_cleaned_data = super().clean()
        pswd = all_cleaned_data["password"]
        conf = all_cleaned_data["confirm_password"]

        if pswd != conf:
            raise forms.ValidationError('Password do not match!')

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

test5/my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm, UserProfileForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    return render(request, 'my_app/index.html')


@login_required
def special(request):
    return HttpResponse('You are logged in, awesome!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'my_app/registration.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                HttpResponse('Account not active')

        else:
            print('Someone tried to login and failed')
            print('Username: {} and password: {}'.format(username, password))

    else:
        return render(request, 'my_app/login.html', {})

test5/templates/my_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Base</title>
</head>

<body>
  <nav class="navbar">
    <div class="container">
      <ul class="navbar__list">
        <li class="navbar__link"><a href="{% url 'index' %}">HOME</a></li>
        <li class="navbar__link"><a href="{% url 'admin:index' %}">ADMIN</a></li>
        <li class="navbar__link"><a href="{% url 'my_app:register' %}">REGISTER</a></li>

        {% if user.is_authenticated %}
        <li class="navbar__link"><a href="{% url 'logout' %}">Logout</a></li>

        {% else %}
        <li class="navbar__link"><a href="{% url 'my_app:user_login' %}">Login</a></li>

        {% endif %}

      </ul>
    </div>
  </nav>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>

</body>

</html>

test5/templates/my_app/index.html
{% extends "my_app/base.html" %}
{% block body_block %}

<div>
  <h1>Django level five</h1>
</div>

{% endblock %}

test5/templates/my_app/login.html
{% extends 'my_app/base.html' %}
{% block body_block %}

<div>
  <h1>Please, Login</h1>
  <form action="{% url 'my_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter password">

    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

test5/templates/my_app/registration.html
<!DOCTYPE html>
{% extends 'my_app/base.html' %}
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
  {% block body_block %}
  <div>
    {% if registered %}
    <h1>Thank you for regsistration!</h1>
    {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form</h3>

    <form enctype="multipart/form-data" method="post">
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      {% csrf_token %}
      <input type="submit" name="" id="Register">
    </form>

    {% endif %}
  </div>
  {% endblock %}
</body>

</html>